services:
  - type: web
    name: claimcracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true
